### ISSUE TITLE
Plugins failing on Jenkins startup

### ISSUE THREAD

**Issue by sunderhill-gft** [tranquilitybase-io/tb-jenkins#15]
The LDAP and Blue Ocean plugins appear to be failing on Jenkins startup - see errors below. Investigate why.
The version of Blue Ocean seems to be out of date. May need to add versions to plugins.txt
The LDAP plugin seems to require a newer version of Jenkins. Update Jenkins version to latest stable
```
jenkins-master | 2020-11-26 14:57:07.238+0000 [id=26]   SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin LDAP Plugin v1.26 (ldap)
jenkins-master | java.io.IOException: Failed to load: LDAP Plugin (1.26)
jenkins-master |  - Jenkins (2.235.3) or higher required
jenkins-master |        at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:934)
jenkins-master |        at hudson.PluginManager$2$1$1.run(PluginManager.java:548)
jenkins-master |        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
jenkins-master |        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
jenkins-master |        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
jenkins-master |        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
jenkins-master |        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
jenkins-master |        at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
jenkins-master |        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jenkins-master |        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jenkins-master |        at java.lang.Thread.run(Thread.java:748)
jenkins-master | 2020-11-26 14:57:07.250+0000 [id=28]   SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Blue Ocean v1.24.3 (blueocean)
jenkins-master | java.io.IOException: Failed to load: Blue Ocean (1.24.3)
jenkins-master |  - Update required: DEPRECATED Blue Ocean Executor Info (1.24.2) to be updated to 1.24.3 or higher
jenkins-master |        at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:934)
jenkins-master |        at hudson.PluginManager$2$1$1.run(PluginManager.java:548)
jenkins-master |        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
jenkins-master |        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
jenkins-master |        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
jenkins-master |        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
jenkins-master |        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
jenkins-master |        at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
jenkins-master |        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jenkins-master |        at java.util.concurrent.ThreadPoolExecutor$
```

**Comment by harris-agyeman** [comment]
completed !
